import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://kawisoft.tis.cs.umss.edu.bo/');
  await page.getByRole('banner').getByRole('link', { name: 'Iniciar sesión' }).click();
  await page.getByRole('textbox', { name: 'Correo institucional' }).click();
  await page.getByRole('textbox', { name: 'Correo institucional' }).fill('cttandrea34@gmail.com');
  await page.getByRole('textbox', { name: 'Contraseña' }).click();
  await page.getByRole('textbox', { name: 'Contraseña' }).fill('andy2000');
  await page.getByRole('button', { name: 'Iniciar sesión → en Dev' }).click();
  await page.getByRole('button', { name: 'Añadir proyecto' }).click();
  await page.getByRole('textbox', { name: 'ej. Sistema de Panel Nexus' }).click();
  await page.getByRole('textbox', { name: 'ej. Sistema de Panel Nexus' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'ej. Sistema de Panel Nexus' }).fill('D');
  await page.getByRole('textbox', { name: 'ej. Sistema de Panel Nexus' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'ej. Sistema de Panel Nexus' }).fill('Desarrollo de ');
  await page.getByRole('textbox', { name: 'ej. Sistema de Panel Nexus' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'ej. Sistema de Panel Nexus' }).fill('Desarrollo de S');
  await page.getByRole('textbox', { name: 'ej. Sistema de Panel Nexus' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'ej. Sistema de Panel Nexus' }).fill('Desarrollo de Sistema ');
  await page.getByRole('textbox', { name: 'ej. Sistema de Panel Nexus' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'ej. Sistema de Panel Nexus' }).fill('Desarrollo de Sistema O');
  await page.getByRole('textbox', { name: 'ej. Sistema de Panel Nexus' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'ej. Sistema de Panel Nexus' }).fill('Desarrollo de Sistema Odontologico');
  await page.getByRole('textbox', { name: 'Un breve resumen de una línea' }).click();
  await page.getByRole('textbox', { name: 'Un breve resumen de una línea' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Un breve resumen de una línea' }).fill('ES');
  await page.getByRole('textbox', { name: 'Un breve resumen de una línea' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Un breve resumen de una línea' }).fill('ES un sistema para un consultorio odontologico');
  await page.getByRole('button').first().click();
  await page.getByRole('button', { name: 'Cargar desde .txt' }).click();
  await page.getByRole('button', { name: 'Cargar desde .txt' }).setInputFiles('env.txt');
  await page.getByRole('button', { name: '+ Añadir Tech' }).click();
  await page.getByRole('textbox', { name: 'Escribe una tecnología y' }).fill('java');
  await page.getByRole('textbox').nth(5).fill('2026-01-06');
  await page.locator('input[type="date"]').nth(1).fill('2026-08-12');
  await page.getByRole('textbox', { name: 'https://github.com/' }).click();
  await page.getByRole('textbox', { name: 'https://github.com/' }).fill('https://github.com/4ndrea5');
  await page.getByRole('button', { name: 'Publicar Proyecto' }).click();
});