import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://kawisoft.tis.cs.umss.edu.bo/');
  await page.getByRole('banner').getByRole('link', { name: 'Iniciar sesión' }).click();
  await page.getByRole('textbox', { name: 'Correo institucional' }).click();
  await page.getByRole('textbox', { name: 'Correo institucional' }).fill('cttandrea34@gmail.com');
  await page.getByRole('textbox', { name: 'Contraseña' }).click();
  await page.getByRole('textbox', { name: 'Contraseña' }).fill('andy2000');
  await page.getByRole('textbox', { name: 'Contraseña' }).press('Enter');
  await page.getByRole('button', { name: 'Iniciar sesión → en Dev' }).click();
  await page.getByRole('button', { name: 'Editar bio' }).click();
  await page.getByRole('button', { name: 'Cerrar aviso' }).click();
  await page.getByRole('textbox').nth(2).click();
  await page.getByRole('textbox').nth(2).press('CapsLock');
  await page.getByRole('textbox').nth(2).fill('T');
  await page.getByRole('textbox').nth(2).press('CapsLock');
  await page.getByRole('textbox').nth(2).fill('Terrazas');
  await page.getByRole('button', { name: 'Editar foto de perfil' }).click();
  await page.locator('.lucide.lucide-upload').click();
  await page.locator('body').setInputFiles('Ribbit’s door icon (TADC).jpg');
  await page.getByRole('button', { name: 'Confirmar' }).click();
  await page.locator('textarea').click();
  await page.locator('textarea').press('CapsLock');
  await page.locator('textarea').fill('S');
  await page.locator('textarea').press('CapsLock');
  await page.getByText('S', { exact: true }).fill('Soy desarrolladora frontend y backend ');
  await page.getByText('Telefono de contactoEstado').click();
  await page.locator('section').filter({ hasText: 'Informacion de ContactoCorreo' }).locator('input[type="text"]').fill('65435172');
  await page.getByRole('textbox', { name: 'Ej: Especializacion en' }).click();
  await page.getByRole('textbox', { name: 'Ej: Especializacion en' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Ej: Especializacion en' }).fill('E');
  await page.getByRole('textbox', { name: 'Ej: Especializacion en' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Ej: Especializacion en' }).fill('Especialista en ');
  await page.getByRole('textbox', { name: 'Ej: Especializacion en' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Ej: Especializacion en' }).fill('Especialista en F');
  await page.getByRole('textbox', { name: 'Ej: Especializacion en' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Ej: Especializacion en' }).fill('Especialista en Frontend');
  await page.getByRole('textbox', { name: 'Ej: Desarrollador Semi Senior' }).click();
  await page.getByRole('textbox', { name: 'Ej: Desarrollador Semi Senior' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Ej: Desarrollador Semi Senior' }).fill('Q');
  await page.getByRole('textbox', { name: 'Ej: Desarrollador Semi Senior' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Ej: Desarrollador Semi Senior' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Ej: Desarrollador Semi Senior' }).fill('QA');
  await page.getByRole('textbox', { name: 'Ej: Desarrollador Semi Senior' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Ej: Desarrollador Semi Senior' }).fill('QAtester');
  await page.locator('div:nth-child(2) > .mt-4 > .flex.items-center.gap-2.rounded-2xl.border.border-dashed > .inline-flex').click();
  await page.getByRole('button', { name: 'Personalizado' }).click();
  await page.locator('div:nth-child(5) > .flex > .relative').click();
  await page.locator('div:nth-child(8) > .flex > .relative').click();
  await page.getByRole('button', { name: 'Guardar' }).click();
  await page.getByRole('button', { name: 'Entendido' }).click();
});  