import { test, expect } from '@playwright/test';
import { login, setFirstFileInput } from './helpers.js';

test('TC-11 Registrar experiencia laboral', async ({ page }) => {
  await login(page);
  await page.getByRole('button', { name: 'Experiencia' }).click();
  await page.getByRole('button', { name: 'Subir Nuevo PDF, PNG, JPG o' }).click();
  await page.getByRole('textbox', { name: 'Ej: SYSTEM ARCHITECTURE, QA' }).click();
  await page.getByRole('textbox', { name: 'Ej: SYSTEM ARCHITECTURE, QA' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Ej: SYSTEM ARCHITECTURE, QA' }).fill('Q');
  await page.getByRole('textbox', { name: 'Ej: SYSTEM ARCHITECTURE, QA' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Ej: SYSTEM ARCHITECTURE, QA' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Ej: SYSTEM ARCHITECTURE, QA' }).fill('QA');
  await page.getByRole('textbox', { name: 'Ej: SYSTEM ARCHITECTURE, QA' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Ej: SYSTEM ARCHITECTURE, QA' }).fill('QAtester');
  await page.getByRole('textbox', { name: 'Ej: Google, Amazon, Startup' }).click();
  await page.getByRole('textbox', { name: 'Ej: Google, Amazon, Startup' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Ej: Google, Amazon, Startup' }).fill('G');
  await page.getByRole('textbox', { name: 'Ej: Google, Amazon, Startup' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Ej: Google, Amazon, Startup' }).fill('Google');
  await page.getByRole('textbox', { name: 'Ej: Google, Amazon, Startup' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Ej: Frontend Developer' }).click();
  await page.getByRole('textbox', { name: 'Ej: Frontend Developer' }).fill('Q');
  await page.getByRole('textbox', { name: 'Ej: Frontend Developer' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Ej: Frontend Developer' }).fill('Q');
  await page.getByRole('textbox', { name: 'Ej: Frontend Developer' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Ej: Frontend Developer' }).fill('QA');
  await page.getByRole('textbox', { name: 'Ej: Frontend Developer' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Ej: Frontend Developer' }).fill('QAtester');
  await page.getByRole('textbox', { name: 'mm/dd/aaaa' }).first().click();
  await page.getByRole('textbox', { name: 'mm/dd/aaaa' }).first().press('NumLock');
  await page.getByRole('textbox', { name: 'mm/dd/aaaa' }).first().fill('09/05/2021');
  await page.getByRole('textbox', { name: 'mm/dd/aaaa' }).nth(1).click();
  await page.getByRole('textbox', { name: 'mm/dd/aaaa' }).nth(1).fill('10/09/2026');
  await page.getByRole('textbox', { name: 'Resume tus responsabilidades' }).click();
  await page.getByRole('textbox', { name: 'Resume tus responsabilidades' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Resume tus responsabilidades' }).fill('F');
  await page.getByRole('textbox', { name: 'Resume tus responsabilidades' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Resume tus responsabilidades' }).fill('Fui ');
  await page.getByRole('textbox', { name: 'Resume tus responsabilidades' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Resume tus responsabilidades' }).fill('Fui Q');
  await page.getByRole('textbox', { name: 'Resume tus responsabilidades' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Resume tus responsabilidades' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Resume tus responsabilidades' }).fill('Fui QA');
  await page.getByRole('textbox', { name: 'Resume tus responsabilidades' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Resume tus responsabilidades' }).fill('Fui QAtester de la empresa de google');
  await page.getByText('Haz clic o arrastra el archivo aquíFormato PDF, PNG o JPG (Máx. 5MB)').click();
  await setFirstFileInput(page, 'sample.png');
  await page.getByRole('button', { name: 'Guardar Experiencia' }).click();
});

